import { registerWidget } from "./registry";
import { clockWidgetDefinition } from "../components/widgets/ClockWidget/ClockWidgetDefinition";
import { timerWidgetDefinition } from "../components/widgets/TimerWidget/TimerWidgetDefinition";
import { timelineWidgetDefinition } from "../components/widgets/TimelineWidget/TimelineWidgetDefinition";
import { habitTrackerWidgetDefinition } from "../components/widgets/HabitTrackerWidget/HabitTrackerWidgetDefinition";
import { sleepTrackerWidgetDefinition } from "../components/widgets/SleepTrackerWidget/SleepTrackerWidgetDefinition";
import { focusStreamWidgetDefinition } from "../components/widgets/FocusStreamWidget/FocusStreamWidgetDefinition";
import { contextSwitcherWidgetDefinition } from "../components/widgets/ContextSwitcherWidget/ContextSwitcherWidgetDefinition";
import { departuresWidgetDefinition } from "../components/widgets/DeparturesWidget/DeparturesWidgetDefinition";
import { routesWidgetDefinition } from "../components/widgets/RoutesWidget/RoutesWidgetDefinition";
import { interruptionLoggerWidgetDefinition } from "../components/widgets/InterruptionLoggerWidget/InterruptionLoggerWidgetDefinition";
import { moodTrackerWidgetDefinition } from "../components/widgets/MoodTrackerWidget/MoodTrackerWidgetDefinition";
import { entropyBurdenTrackerWidgetDefinition } from "../components/widgets/EntropyBurdenTrackerWidget/EntropyBurdenTrackerWidgetDefinition";
import { metricGoalTrackerWidgetDefinition } from "../components/widgets/MetricGoalTrackerWidget/MetricGoalTrackerWidgetDefinition";
import { eventLoopLoggerWidgetDefinition } from "../components/widgets/EventLoopLoggerWidget/EventLoopLoggerWidgetDefinition";
import { generationalHistoricalWidgetDefinition } from "../components/widgets/GenerationalHistoricalWidget/GenerationalHistoricalWidgetDefinition";
import { routineWidgetDefinition } from "../components/widgets/RoutineWidget/RoutineWidgetDefinition.ts";
import { modularTaskTrackerWidgetDefinition } from "../components/widgets/ModularTaskTrackerWidget/ModularTaskTrackerWidgetDefinition";
import { weatherWidgetDefinition } from "../components/widgets/WeatherWidget/WeatherWidgetDefinition.ts";
import { activityTrackerWidgetDefinition } from "../components/widgets/ActivityTrackerWidget/ActivityTrackerWidgetDefinition";
import { calendarWidgetDefinition } from "../components/widgets/CalendarWidget/CalendarWidgetDefinition";

registerWidget(clockWidgetDefinition);
registerWidget(timerWidgetDefinition);
registerWidget(timelineWidgetDefinition);
registerWidget(habitTrackerWidgetDefinition);
registerWidget(sleepTrackerWidgetDefinition);
registerWidget(focusStreamWidgetDefinition);
registerWidget(contextSwitcherWidgetDefinition);
registerWidget(departuresWidgetDefinition);
registerWidget(routesWidgetDefinition);
registerWidget(interruptionLoggerWidgetDefinition);
registerWidget(moodTrackerWidgetDefinition);
registerWidget(entropyBurdenTrackerWidgetDefinition);
registerWidget(metricGoalTrackerWidgetDefinition);
registerWidget(eventLoopLoggerWidgetDefinition);
registerWidget(generationalHistoricalWidgetDefinition);
registerWidget(routineWidgetDefinition);
registerWidget(modularTaskTrackerWidgetDefinition);
registerWidget(weatherWidgetDefinition);
registerWidget(activityTrackerWidgetDefinition);
registerWidget(calendarWidgetDefinition);
export { WIDGET_REGISTRY } from "./registry";
